name: Main build

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

env:
  NAMESPACE: galasa-dev

jobs:
    delete-previous-packages:
      name: Delete previous versions
      runs-on: ubuntu-latest
      strategy:
          matrix: 
            name: [galasa-gradle-parent, githash.dev.galasa.githash.gradle.plugin,obr.dev.galasa.obr.gradle.plugin,tests.dev.galasa.tests.gradle.plugin,dev.galasa.gradle.impl,testcatalog.dev.galasa.testcatalog.gradle.plugin,dev.galasa.plugin.common,dev.galasa.plugin.common.impl,dev.galasa.plugin.common.test]

      steps:
        - name: Delete previous versions
          uses: actions/delete-package-versions@v5
          with:
           package-name: 'dev.galasa.${{matrix.name}}'
           package-type: 'maven'

    build-gradle:
        name: build and Test Gradle 
        needs: delete-previous-packages
        if: always()
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup JDK 
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'semeru'
            
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
              with:
                gradle-version: 6.9.2
  
            - name: Test and Build Gradle
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                ORG_GRADLE_PROJECT_signingKeyId:  ${{ secrets.GPG_KEYID }}
                ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
                ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
              run: |
                gradle check publish --scan \
                -PsourceMaven=https://repo.maven.apache.org/maven2/ \
                -PcentralMaven=https://repo.maven.apache.org/maven2/ \
                -PtargetMaven=https://maven.pkg.github.com/${{env.NAMESPACE}}/gradle \
                -PjacocoEnabled=true \
                -PisMainOrRelease=true