#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Managers Main Build

on:
  workflow_call:
    inputs:
      jacoco_enabled:
        description: 'True if Jacoco code coverage should be enabled (set to "false" for release builds)'
        required: false
        default: 'true'
        type: string
      sign_artifacts:
        description: 'True if the artifacts built should be signed (set to "false" for development branch builds)'
        required: false
        default: 'true'
        type: string

env:
  BRANCH: ${{ github.ref_name }}

jobs:

  log-github-ref:
    name: Log the GitHub ref this workflow is running on (Branch or tag that received dispatch)
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub ref of workflow
        run: |
          echo "This workflow is running on GitHub ref ${{ env.BRANCH }}"

  build-managers:
    name: Build Managers source code and Docker image for development Maven registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Download platform from this workflow
        id: download-platform
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts

      - name: Download wrapping artifacts from this workflow
        id: download-wrapping
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts
  
      - name: Download gradle artifacts from this workflow
        id: download-gradle
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts

      - name: Download maven artifacts from this workflow
        id: download-maven
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts

      - name: Download framework artifacts from this workflow
        id: download-framework
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts

      - name: Build Managers source code
        working-directory: modules/managers
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKeyId:  ${{ secrets.GPG_KEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -o pipefail
          gradle -b galasa-managers-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -Dorg.gradle.jvmargs=-Xmx4096M \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/managers/repo \
          -PjacocoEnabled=${{ inputs.jacoco_enabled }} \
          -PisMainOrRelease=${{ inputs.sign_artifacts }} 2>&1 | tee build.log
        
      - name: Upload Gradle build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-gradle-build-log
          path: modules/managers/build.log
          retention-days: 7
          
      - name: Upload Jacoco report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-jacoco-report
          path: ${{ github.workspace }}/galasa-managers-parent/**/**/build/reports/**/*.html
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload managers artifacts
        uses: actions/upload-artifact@v4
        with:
          name: managers
          path: modules/managers/repo

  report-failure:
    name: Report failure in workflow
    runs-on: ubuntu-latest
    needs: [log-github-ref, build-managers]
    if: failure()

    steps:
      - name: Report failure in workflow to Slack
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run : |
          docker run --rm ghcr.io/galasa-dev/galasabld-ibm:main slackpost workflows --repo "galasa" --module "managers" --workflowName "${{ github.workflow }}" --workflowRunNum "${{ github.run_id }}" --ref "${{ env.BRANCH }}" --hook "${{ env.SLACK_WEBHOOK }}"
