#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Managers PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string
      platform-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the platform'
        required: true
        type: string
      wrapping-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the wrapping module'
        required: true
        type: string
      gradle-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the gradle module'
        required: true
        type: string
      maven-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the maven module'
        required: true
        type: string
      framework-artifact-id:
        description: 'The Workflow Run ID of the last workflow containing artifacts for the framework module'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Managers is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The managers module is unchanged"

  build-managers:
    name: Build Managers source code and Docker image
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup JDK 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      # For any modules that were changed in this PR,
      # download their artifacts from this workflow run.

      - name: Download platform from this workflow
        id: download-platform
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts

      - name: Download wrapping artifacts from this workflow
        id: download-wrapping
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts

      - name: Download gradle artifacts from this workflow
        id: download-gradle
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts

      - name: Download maven artifacts from this workflow
        id: download-maven
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts

      - name: Download framework artifacts from this workflow
        id: download-framework
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts

      # For any modules that weren't changed in this PR,
      # download artifacts from the last successful workflow.

      - name: Download platform from last successful workflow
        if: ${{ steps.download-platform.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: platform
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.platform-artifact-id }}

      - name: Download wrapping artifacts from last successful workflow
        if: ${{ steps.download-wrapping.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: wrapping
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.wrapping-artifact-id }}
  
      - name: Download gradle artifacts from last successful workflow
        if: ${{ steps.download-gradle.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: gradle
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.gradle-artifact-id }}

      - name: Download maven artifacts from last successful workflow
        if: ${{ steps.download-maven.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: maven
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.maven-artifact-id }}

      - name: Download framework artifacts from last successful workflow
        if: ${{ steps.download-framework.outcome == 'failure' }}
        uses: actions/download-artifact@v4
        with:
          name: framework
          path: modules/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ inputs.framework-artifact-id }}
      
      - name: Build Managers source code
        working-directory: modules/managers
        run: |
          set -o pipefail
          gradle -b galasa-managers-parent/build.gradle check publish --info \
          --no-daemon --console plain \
          -Dorg.gradle.jvmargs=-Xmx4096M \
          -PsourceMaven=${{ github.workspace }}/modules/artifacts \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/managers/repo 2>&1 | tee build.log

      - name: Upload Gradle build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-gradle-build-log
          path: modules/managers/build.log
          retention-days: 7
            
      - name: Upload Jacoco report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: managers-jacoco-report
          path: modules/managers/galasa-managers-parent/**/**/build/reports/**/*.html
          retention-days: 7
          if-no-files-found: ignore

      - name: Upload managers artifacts
        uses: actions/upload-artifact@v4
        with:
          name: managers
          path: modules/managers/repo