#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Platform PR Build

on:
  workflow_call:
    inputs:
      changed:
        description: 'True if this module has been changed and should be rebuilt'
        required: true
        type: string

jobs:

  log-unchanged:
    name: Platform is unchanged
    if: ${{ inputs.changed == 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: Log this module is unchanged
        run: |
          echo "The gradle module is unchanged"

  build-platform:
    name: Build Platform
    if: ${{ inputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
          cache-disabled: true

      - name: Build Platform
        working-directory: modules/platform
        run: |
          gradle -b dev.galasa.platform/build.gradle build check publish --info \
          --no-daemon --console plain \
          -PsourceMaven=https://repo.maven.apache.org/maven2/ \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/modules/platform/repo

      - name: Upload Platform artifacts
        uses: actions/upload-artifact@v4
        with:
          name: platform
          path: modules/platform/repo